### ISSUE TITLE
ARM Outputs not working on Hosted Linux Agent

### ISSUE THREAD

**Issue by saikiranchalla1** [keesschollaart81/vsts-arm-outputs#11]
The ARM Outputs extension doesn't seem to work with Hosted Linux agent in VSTS. Is there a work around for this? Will the support be added in future?

**Comment by keesschollaart81** [comment]
Hi. Thats true. This is because the task is based on the Powershell3 handler. There is yet no support for Powershell-based extensions running on Powershell Core. Please take a look at this thread: https://github.com/Microsoft/vsts-task-lib/issues/314

What I could do is port this extension to Typescript, I wont have the time to do this anytime soon (but feel free to pop a PR :-) ). Next to that, I expect that a pwsh host/handler for custom extensions will be available any time soon...
