### ISSUE TITLE
Doesn't handle other Azure Clouds

### ISSUE THREAD

**Issue by wahidsaleemi** [keesschollaart81/vsts-arm-outputs#38]
Looks like the management endpoint is hard-coded for AzureCloud (Azure Commercial). We tried to use it on AzureUSGovernment (Azure Government) and it was pointing at the wrong management endpoint.

Would be nice if it could handle all the Azure Clouds (Gov, China, Germany, Azure Stack, etc.)

**Comment by aholler2** [comment]
This is also an issue for our organization to use for AzureChina.

**Comment by keesschollaart81** [comment]
Awesome, will release this feature later this week after I ran it for a couple of days agains my ACC ring

**Comment by keesschollaart81** [comment]
This should now be available in production. I don't have access to other clouds than the normal Azure one so please test for me if it works!

**Comment by aholler2** [comment]
Unfortunately because I was not able to test locally, there was a piece missing to work with other Azure clouds. I have since setup private extension testing and fixed the issue. I initially skipped adding multi-cloud configuration to the ResourceManagementClient. I had assumed that it would get environment information from the passed credentials but that assumption was wrong.
