### ISSUE TITLE
Variables available only within phase

### ISSUE THREAD

**Issue by mickeycohen** [keesschollaart81/vsts-arm-outputs#6]
It appears the variables are only available within the same phase and cannot be used in the next phases
Is there anything that can be done about this?

Thanks

**Comment by weznagwama** [comment]
My limited understanding of phases is that they're seperate agent(s), and process.

E.g. if you have 2 phases, that's 2 separate powershell instances. The variable output here is limited to that single instance.

**Comment by keesschollaart81** [comment]
That is correct. It's not possible yet, however, they are working on in. Please keep track of this issue: https://github.com/Microsoft/vsts-tasks/issues/4743 

In preparation to this, starting from version 4 outputs are marked as 'isOutput=true'. This seems to be the way it needs to be implemented (checkout the YAML docs [here](https://docs.microsoft.com/en-us/vsts/pipelines/process/multiple-phases?view=vsts&tabs=yaml#conditions))

**Comment by NSouth** [comment]
@keesschollaart81 , to clarify, do "phases" here correspond to "jobs", as in the "Run on agent" job pictured blow? We want to be sure that these variables are scoped to the current Stage so that if two Stages are deploying the same ARM template at the same time to different environments, one deployment doesn't set the variable of the same name used by another deployment. In other words, we don't want the variable to be available across the entire release pipeline. By the way, thanks for this tool!

![image](https://user-images.githubusercontent.com/11379932/45185006-b154dc80-b1f6-11e8-88ea-c6a149aa2bf2.png)

**Comment by keesschollaart81** [comment]
Yes, that is a good question.  

- In v4.0 outputs are **not** available across multiple agent-phases in a release pipeline

I ended up not implementing the ```isOutput=true'``` because I was not able to get this actually working. So this is not implemented in v4.0 ([link](https://github.com/keesschollaart81/vsts-arm-outputs/blob/v4.0/arm-outputs/Out-ARMOutput.ps1#L77)) because I did not want to break stuff later on when they make this available.

If this multi-phase variable feature becomes available, I'd love to make this part of this step but then it would be a toggle or something like that.

**Comment by akalcik** [comment]
There is possibility to set the scope of the variables (_Stage_ or _Pipeline_). For the same reason should be possible to set the output variables for the whole pipeline. Maybe a checkbox should be checked if it is desired. The conflicts between two stages can protected by prefixes, which this tool already support.

**Comment by keesschollaart81** [comment]
I'll reopen this if this issue mentioned [above](https://github.com/keesschollaart81/vsts-arm-outputs/issues/6#issuecomment-417640927) progresses.
